import Head from 'next/head'
import styles from '../styles/Home.module.css'
import clientPromise, { isMongoDBConnected } from '../lib/mongodb';

interface Props {
  isConnected: boolean;
}

export default function Home({ isConnected }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wannabe fullstack project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {isConnected.toString()}
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const client = await clientPromise

  return {
    props: {
      isConnected: isMongoDBConnected(client),
    },
  }
}
